"""add remember me to auth sessions

Revision ID: 6814309891f6
Revises: 587479406ad0
Create Date: 2026-09-09 07:03:16.281613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6814309891f6'
down_revision: Union[str, Sequence[str], None] = '587479406ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "auth_sessions",
    sa.Column(
        "remember_me",
        sa.Boolean(),
        server_default=sa.false(),
        nullable=False,
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    "auth_sessions",
    "remember_me",
    server_default=None,
)
    # ### end Alembic commands ###
