"""Add session user agent

Revision ID: 76442306e029
Revises: 0fb29f697369
Create Date: 2026-09-15 10:46:17.373238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76442306e029'
down_revision: Union[str, Sequence[str], None] = '0fb29f697369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('user_agent', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_sessions', 'user_agent')
    # ### end Alembic commands ###
