"""add message replies

Revision ID: 8c357ce64b1d
Revises: 9664e6a4656b
Create Date: 2026-09-07 19:19:41.868400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c357ce64b1d'
down_revision: Union[str, Sequence[str], None] = '9664e6a4656b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_message_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_column('messages', 'reply_to_message_id')
    # ### end Alembic commands ###
